-- MHChub document library schema.
-- Stores document metadata and audit fields in the dedicated `mhchub` database.

CREATE TABLE IF NOT EXISTS documents (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT 'general',
  department_id VARCHAR(64) NOT NULL DEFAULT 'company',
  department_name VARCHAR(191) NULL,
  language VARCHAR(16) NOT NULL DEFAULT 'vi',
  version VARCHAR(64) NULL DEFAULT '1.0',
  original_name VARCHAR(255) NULL,
  file_name VARCHAR(255) NULL,
  mime_type VARCHAR(191) NULL,
  size BIGINT NOT NULL DEFAULT 0,
  uploaded_at DATETIME NULL,
  url VARCHAR(500) NULL,
  source VARCHAR(64) NULL,
  source_path VARCHAR(500) NULL,
  storage_path VARCHAR(500) NULL,
  preview_file_name VARCHAR(255) NULL,
  preview_mime_type VARCHAR(191) NULL,
  preview_url VARCHAR(500) NULL,
  preview_status VARCHAR(64) NULL,
  preview_error VARCHAR(500) NULL,
  preview_generated_at DATETIME NULL,
  preview_size BIGINT NULL,
  created_by VARCHAR(191) NULL,
  created_by_name VARCHAR(191) NULL,
  created_by_role VARCHAR(32) NULL,
  created_at DATETIME NULL,
  updated_by VARCHAR(191) NULL,
  updated_by_name VARCHAR(191) NULL,
  updated_by_role VARCHAR(32) NULL,
  updated_at DATETIME NULL,
  KEY idx_documents_category (category),
  KEY idx_documents_department (department_id),
  KEY idx_documents_uploaded_at (uploaded_at),
  KEY idx_documents_updated_at (updated_at),
  KEY idx_documents_title (title(191)),
  KEY idx_documents_original_name (original_name(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
