-- MHChub Safety operations schema.
-- Stores Safety - 6S operational records in the dedicated `mhchub` database.

CREATE TABLE IF NOT EXISTS safety_warnings (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(120) NOT NULL,
  subcategory VARCHAR(120) NULL,
  department VARCHAR(120) NOT NULL,
  area VARCHAR(191) NULL,
  risk_probability INT NOT NULL DEFAULT 1,
  risk_consequence INT NOT NULL DEFAULT 1,
  risk_score INT NOT NULL DEFAULT 1,
  risk_level VARCHAR(64) NOT NULL DEFAULT 'Thấp',
  description TEXT NOT NULL,
  current_control TEXT NULL,
  proposed_action TEXT NULL,
  responsible_person VARCHAR(191) NULL,
  deadline DATE NULL,
  reporter_name VARCHAR(191) NULL,
  evidence_notes TEXT NULL,
  related_standard VARCHAR(255) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'Mở',
  approval_status VARCHAR(64) NOT NULL DEFAULT 'Chờ duyệt',
  rejection_reason TEXT NULL,
  submitted_by_dept VARCHAR(120) NULL,
  submitted_by_id VARCHAR(64) NULL,
  submitted_by_name VARCHAR(191) NULL,
  created_by_name VARCHAR(191) NULL,
  updated_by_name VARCHAR(191) NULL,
  deleted_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_safety_warnings_code (code),
  KEY idx_safety_warnings_department (department),
  KEY idx_safety_warnings_approval (approval_status),
  KEY idx_safety_warnings_status (status),
  KEY idx_safety_warnings_deadline (deadline),
  KEY idx_safety_warnings_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_incidents (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  type VARCHAR(120) NOT NULL,
  severity VARCHAR(64) NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'Đang xử lý',
  department VARCHAR(120) NOT NULL,
  area VARCHAR(191) NULL,
  description TEXT NOT NULL,
  occurred_date DATE NULL,
  occurred_time VARCHAR(16) NULL,
  reporter_name VARCHAR(191) NULL,
  reporter_phone VARCHAR(64) NULL,
  handler_name VARCHAR(191) NULL,
  witnesses TEXT NULL,
  body_parts_affected_json TEXT NULL,
  first_aid_given TINYINT(1) NOT NULL DEFAULT 0,
  root_cause_category VARCHAR(191) NULL,
  root_cause_detail TEXT NULL,
  immediate_action TEXT NULL,
  corrective_action TEXT NULL,
  preventive_action TEXT NULL,
  estimated_cost DECIMAL(14,2) NULL,
  approval_status VARCHAR(64) NOT NULL DEFAULT 'Chờ duyệt',
  rejection_reason TEXT NULL,
  submitted_by_dept VARCHAR(120) NULL,
  submitted_by_id VARCHAR(64) NULL,
  submitted_by_name VARCHAR(191) NULL,
  created_by_name VARCHAR(191) NULL,
  updated_by_name VARCHAR(191) NULL,
  deleted_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_safety_incidents_code (code),
  KEY idx_safety_incidents_department (department),
  KEY idx_safety_incidents_approval (approval_status),
  KEY idx_safety_incidents_status (status),
  KEY idx_safety_incidents_occurred_date (occurred_date),
  KEY idx_safety_incidents_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_kpi_entries (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  entry_type VARCHAR(120) NOT NULL,
  period_type VARCHAR(64) NOT NULL,
  period VARCHAR(64) NOT NULL,
  department_code VARCHAR(120) NOT NULL,
  division_code VARCHAR(120) NULL,
  value DECIMAL(14,4) NOT NULL DEFAULT 0,
  target DECIMAL(14,4) NULL,
  unit VARCHAR(64) NULL,
  notes TEXT NULL,
  approval_status VARCHAR(64) NOT NULL DEFAULT 'pending_l1',
  rejection_reason TEXT NULL,
  rejected_by_level VARCHAR(32) NULL,
  submitted_by_id VARCHAR(64) NULL,
  submitted_by_name VARCHAR(191) NULL,
  submitted_by_dept VARCHAR(120) NULL,
  l1_approved_by_id VARCHAR(64) NULL,
  l1_approved_by_name VARCHAR(191) NULL,
  l1_approved_at DATETIME NULL,
  l2_approved_by_id VARCHAR(64) NULL,
  l2_approved_by_name VARCHAR(191) NULL,
  l2_approved_at DATETIME NULL,
  created_by_name VARCHAR(191) NULL,
  updated_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_safety_kpi_entries_code (code),
  KEY idx_safety_kpi_period (period_type, period),
  KEY idx_safety_kpi_department (department_code),
  KEY idx_safety_kpi_approval (approval_status),
  KEY idx_safety_kpi_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_checklist_submissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  department_code VARCHAR(120) NOT NULL,
  period VARCHAR(64) NOT NULL,
  template_id VARCHAR(120) NULL,
  item_id INT NOT NULL,
  checked TINYINT(1) NOT NULL DEFAULT 0,
  result_status VARCHAR(32) NULL,
  submitted_by_id VARCHAR(64) NULL,
  submitted_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uq_safety_checklist_item (department_code, period, item_id),
  KEY idx_safety_checklist_period (period),
  KEY idx_safety_checklist_department (department_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_approval_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  entity_type VARCHAR(64) NOT NULL,
  entity_id VARCHAR(64) NOT NULL,
  entity_code VARCHAR(64) NULL,
  action VARCHAR(64) NOT NULL,
  actor_id VARCHAR(64) NULL,
  actor_name VARCHAR(191) NULL,
  actor_role VARCHAR(32) NULL,
  actor_dept VARCHAR(120) NULL,
  reason TEXT NULL,
  created_at DATETIME NOT NULL,
  KEY idx_safety_approval_entity (entity_type, entity_id),
  KEY idx_safety_approval_created_at (created_at),
  KEY idx_safety_approval_actor (actor_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_notifications (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  type VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  page VARCHAR(120) NULL,
  for_roles VARCHAR(255) NULL,
  for_dept VARCHAR(120) NULL,
  entity_type VARCHAR(64) NULL,
  entity_code VARCHAR(64) NULL,
  read_by_user_ids TEXT NULL,
  created_at DATETIME NOT NULL,
  KEY idx_safety_notifications_target (for_dept, created_at),
  KEY idx_safety_notifications_entity (entity_type, entity_code),
  KEY idx_safety_notifications_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_reports (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(120) NOT NULL,
  period VARCHAR(64) NULL,
  department VARCHAR(120) NOT NULL,
  creator VARCHAR(191) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'Nháp',
  notes TEXT NULL,
  created_by_id VARCHAR(64) NULL,
  created_by_name VARCHAR(191) NULL,
  updated_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_safety_reports_code (code),
  KEY idx_safety_reports_department (department),
  KEY idx_safety_reports_period (period),
  KEY idx_safety_reports_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_training_courses (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(120) NULL,
  trainer VARCHAR(191) NULL,
  duration VARCHAR(64) NULL,
  department VARCHAR(120) NOT NULL,
  enrolled INT NOT NULL DEFAULT 0,
  completed INT NOT NULL DEFAULT 0,
  due_date DATE NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'Chưa bắt đầu',
  notes TEXT NULL,
  created_by_id VARCHAR(64) NULL,
  created_by_name VARCHAR(191) NULL,
  updated_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_safety_training_code (code),
  KEY idx_safety_training_department (department),
  KEY idx_safety_training_status (status),
  KEY idx_safety_training_due_date (due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_attachments (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  entity_type VARCHAR(64) NOT NULL,
  entity_id VARCHAR(64) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  object_path VARCHAR(500) NOT NULL,
  content_type VARCHAR(191) NULL,
  size_bytes BIGINT NOT NULL DEFAULT 0,
  uploaded_by_id VARCHAR(64) NULL,
  uploaded_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  deleted_by_id VARCHAR(64) NULL,
  deleted_by_name VARCHAR(191) NULL,
  KEY idx_safety_attachments_entity (entity_type, entity_id),
  KEY idx_safety_attachments_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS safety_meetings (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  period VARCHAR(8) NOT NULL,
  type VARCHAR(64) NOT NULL DEFAULT 'monthly',
  title VARCHAR(255) NOT NULL,
  meeting_date DATE NULL,
  start_time VARCHAR(8) NOT NULL DEFAULT '08:00',
  end_time VARCHAR(8) NOT NULL DEFAULT '09:00',
  location VARCHAR(191) NULL,
  chairperson VARCHAR(191) NULL,
  participants JSON NULL,
  agenda JSON NULL,
  content_summary TEXT NULL,
  decisions TEXT NULL,
  action_items JSON NULL,
  attached_plan_id VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'planned',
  approved_by_id VARCHAR(64) NULL,
  approved_by_name VARCHAR(191) NULL,
  approved_at DATETIME NULL,
  created_by_id VARCHAR(64) NULL,
  created_by_name VARCHAR(191) NULL,
  deleted_by_name VARCHAR(191) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_safety_meetings_code (code),
  KEY idx_safety_meetings_period (period),
  KEY idx_safety_meetings_status (status),
  KEY idx_safety_meetings_type (type),
  KEY idx_safety_meetings_meeting_date (meeting_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id VARCHAR(64) NOT NULL PRIMARY KEY,
  display_name VARCHAR(191) NULL,
  email VARCHAR(191) NULL,
  phone VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL,
  KEY idx_user_profiles_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
